# Generated by Django 5.2.17 on 2026-10-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='deal_status',
            field=models.CharField(choices=[('active', 'active'), ('reserved', 'reserved'), ('sold', 'sold'), ('cancelled', 'cancelled')], default='active', max_length=20),
        ),
    ]
