# Generated by Django 5.2.17 on 2026-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_options_remove_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('sold', 'sold'), ('reserved', 'reserved'), ('hidden', 'hidden')], default='active', max_length=50),
        ),
    ]
